FROM node:12-alpine

ENV TYPEORM_ENTITIES=dist/**/*.entity.js
ENV TYPEORM_SYNCHRONIZE=true
ENV NODE_ENV=development

RUN mkdir -p /usr/app
WORKDIR /usr/app

COPY package.json yarn.lock tsconfig.json tsconfig.build.json ./
COPY src ./src
COPY public ./public
COPY views ./views
COPY gameStateFile.json ./gameStateFile.json

RUN yarn
RUN yarn build

EXPOSE 3000

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && yarn start:prod