version: "3"
services:

  nestjs:
    build:
      dockerfile: ./Dockerfile.prod
    env_file:
      - ./web-app/.env.prod
    expose:
      - 3000

  postgres:
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    env_file:
      - ./.docker/db/.env.db.prod

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./.docker/nginx/
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - nestjs
    restart: always

volumes:
  db-data-prod:
