FROM node:12-alpine

ENV TYPEORM_ENTITIES=dist/**/*.entity.js
ENV TYPEORM_SUBSCRIBERS=dist/**/*.subscriber.js
ENV TYPEORM_SYNCHRONIZE=true
ENV NODE_ENV=development

RUN mkdir -p /usr/web-app
WORKDIR /usr/web-app

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && yarn && yarn build && yarn start:dev
