name: Web app EC2 deployment
on:
  push:
    branches:
    - feature-hook-mobile-app-to-api # TODO change me back to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging AWS
    
    steps:
      - uses: actions/checkout@v2 

      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
            HOSTNAME : ${{ secrets.AWS_EC2_PUBLIC_IP }}
            USERNAME : ${{ secrets.AWS_EC2_USERNAME }}
            WEBAPP_ENV_VARS: ${{ secrets.WEBAPP_ENV_VARS }}
            POSTGRES_ENV_VARS: ${{ secrets.POSTGRES_ENV_VARS }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          echo "$WEBAPP_ENV_VARS" > ./web-app/.env.prod.dist
          echo "$POSTGRES_ENV_VARS" > ./.docker/db/.env.db.prod.dist
          rsync --delete -r -e "ssh -o StrictHostKeyChecking=no -i private_key" --exclude="mobile-app/*" --filter=':- web-app/.gitignore' ./ ${USERNAME}@${HOSTNAME}:~/Hex
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
            cd ~/Hex &&
            mv ./web-app/.env.prod.dist ./web-app/.env.prod &&
            mv ./.docker/db/.env.db.prod.dist ./.docker/db/.env.db.prod &&
            sudo docker-compose -f docker-compose.base.yaml -f docker-compose.prod.yaml up -d --build 
          '